# Generated by Django 2.0.2 on 2018-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SexistWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('user_full_name', models.CharField(max_length=255, null=True)),
                ('isRetweet', models.BooleanField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sentiment', models.CharField(max_length=2, null=True)),
                ('userIcon', models.CharField(max_length=255, null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('tweet_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
