# Generated by Django 2.0.2 on 2018-10-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='dummy',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
