# Generated by Django 2.1.4 on 2019-01-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_auto_20190112_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='alternativeName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='office_level',
            field=models.CharField(choices=[('Federal', 'Federal'), ('State', 'State'), ('Local', 'Local')], max_length=10, null=True),
        ),
    ]
