# Generated by Django 2.0.2 on 2018-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_auto_20180310_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='isRetweet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
