# Generated by Django 2.0.2 on 2018-12-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_tweet_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='dummy',
        ),
    ]
