# Generated by Django 2.1.4 on 2019-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_auto_20190112_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='political_party',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='office_level',
            field=models.CharField(choices=[('Federal', 'Federal'), ('State', 'State'), ('Local', 'Local')], max_length=255, null=True),
        ),
    ]
