# Generated by Django 2.0.2 on 2018-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_tweet_isretweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Politican',
            new_name='Politician',
        ),
    ]
