# Generated by Django 2.1.4 on 2019-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_auto_20190112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
