# Generated by Django 2.0.2 on 2018-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_auto_20180310_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
