# Generated by Django 2.1.4 on 2018-12-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0005_auto_20181231_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('tweet_count', models.IntegerField(default=0)),
            ],
        ),
    ]
