# Generated by Django 2.1.4 on 2018-12-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0006_twitteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='isRetweet',
            new_name='is_retweet',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='userIcon',
            new_name='user_icon',
        ),
    ]
