# Generated by Django 2.1.4 on 2019-01-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0006_auto_20190114_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=1, null=True),
        ),
    ]
