# Generated by Django 2.1.4 on 2019-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0007_politician_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
