# Generated by Django 2.1.4 on 2018-12-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0007_auto_20181231_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
