# Generated by Django 2.1.4 on 2019-01-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0009_auto_20190114_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='tweet_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
