# Generated by Django 2.1.4 on 2019-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0010_politician_tweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
