# Generated by Django 2.1.4 on 2019-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0011_auto_20190126_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
