# Generated by Django 2.1.4 on 2020-03-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0012_politician_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='clean_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='flirtation',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='identity_attack',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sexually_explicit',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='toxicity',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
