# Generated by Django 2.1.4 on 2020-04-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0015_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
